# Generated by Django 5.1.3 on 2024-12-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_note_ue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='ue',
        ),
    ]
