# Generated by Django 5.1.3 on 2024-12-09 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_note_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.unitedenseignement'),
            preserve_default=False,
        ),
    ]
