# Generated by Django 5.1.3 on 2024-12-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_note_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_academique',
            field=models.IntegerField(default=2024),
        ),
    ]
