# Generated by Django 5.1.3 on 2024-12-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_etudiant_annee_academique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveau',
            options={'ordering': ['niveau_ordre']},
        ),
        migrations.AddField(
            model_name='niveau',
            name='niveau_ordre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=10),
        ),
    ]
