# Generated by Django 5.1.3 on 2024-12-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_niveau_options_niveau_niveau_ordre_and_more'),
    ]

    operations = [
    ]
